# Generated by Django 5.0 on 2023-12-23 12:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TaskDay",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("day", models.CharField(max_length=50)),
                ("done", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("task_name", models.CharField(max_length=50)),
                ("task_day", models.ManyToManyField(to="home.taskday")),
            ],
        ),
    ]
