# Generated by Django 5.0 on 2023-12-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskday',
            name='done_at',
            field=models.DateTimeField(default=None),
        ),
    ]
