# Generated by Django 5.0 on 2023-12-28 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_taskday_done_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskday',
            name='done_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
